# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Docker@2
  inputs:
    containerRegistry: 'defaultConnection'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'defaultConnection'
    repository: 'baran0v / appbackdev'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    arguments: '--platform linux/amd64'