apiVersion: apps/v1
kind: Deployment
metadata:
  name: appbackdev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appbackdev
  template:
    metadata:
      labels:
        app: appbackdev
    spec:
      containers:
      - name: appbackdev
        image: baran0v/appbackdev:latest
        ports:
        - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: appbackdev-service
spec:
  selector:
    app: appbackdev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer